### ISSUE TITLE
Clean up the appearance of the bibliography.

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/iuse2014#25]
Some citations aren't appearing properly.

**Comment by katyhuff** [comment]
Could you be more specific? I think I know which ones look wrong, but I'm not sure whether they're an identical set to yours. 

The ones I think are wrong are these two:

[1] Software carpentry web site.
[10] Greg Wilson. Software carpentry: Lessons learned, 2012.

I think it's because the ''@ online'' decorator is only available in BibLaTeX (not to be confused with BibTeX). I can fix it (with misc) if you tell me those are the only two entries this issue is about. If there are other entries that are bad, let me know which ones.

**Comment by gvwilson** [comment]
I believe these are the only two, and yes, an `@misc` fix would be great.
Thx,
G
